backend:
  name: git-gateway
  branch: master
  commit_messages:
    update: "Update {{collection}} '{{slug}}'"
    delete: "Delete {{collection}} '{{slug}}'"
    create: "Create {{collection}} '{{slug}}'"
    uploadMedia: "[skip ci] Upload '{{path}}'"
    deleteMedia: "[skip ci] Delete '{{path}}'"

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    label_singular: "Post" # Used in the UI, ie: "New Post"
    folder: "content/posts"
    create: true
    slug: "/blog/{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date", 
          name: "date", 
          widget: "datetime",
          date_format: 'YYYY-MM-DD',
          time_format: 'HH:mm',
          format: 'YYYY-MM-DD HH:mm'
        }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Description", name: "description", widget: "markdown", required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }

  - name: "notes"
    label: "Notes"
    label_singular: "Note" # Used in the UI, ie: "New Post"
    folder: "content/notes"
    create: true
    slug: "/notes/{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Date", 
          name: "date", 
          widget: "datetime",
          date_format: 'YYYY-MM-DD',
          time_format: 'HH:mm',
          format: 'YYYY-MM-DD HH:mm'
        }
      - { label: "Labels", name: "labels", widget: "list" }
      - { label: "Description", name: "description", widget: "markdown", required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }
